### ISSUE TITLE
Not compiling

### ISSUE THREAD

**Issue by D063520** [sdauletau/elasticsearch-simple-similarity#2]
hello, 

thank you for providing this example ... when I do mvn clean package I get:

Non-resolvable parent POM: Could not transfer artifact org.elasticsearch.plugin:plugins:pom:2.4.4 from/to central (https://repo.maven.apache.org/maven2): Connect to repo.maven.apache.org:443 [repo.maven.apache.org/151.101.120.215] failed: Connection timed out (Connection timed out) and 'parent.relativePath' points at wrong local POM @ line 12, column 13 -> [Help 2]

do I do something wrong? 

Thank you

**Comment by sdauletau** [comment]
I have updated master branch to support ES 2.4.4 and created 2.4.4 branch.

**Comment by D063520** [comment]
Sorry my mistake, I didn't set the proxy for https.
